In [1]:
#如何将python的列表，转为np的ndarray
import numpy as np
list1 = [1,2,3,4]
print(list1)
oneArray = np.array(list1) 
print(type(oneArray)) 
print(oneArray)
#python list打印出来的元素之间有逗号
# 而ndarray是空格

[1, 2, 3, 4]
<class 'numpy.ndarray'>
[1 2 3 4]


In [2]:
import random
import time
import numpy as np

a = []
for i in range(100000000):
   a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)
#np的运算速度是原生py的5倍

0.7164711952209473 0.15392231941223145


In [3]:
#传入列表变为ndarray
t1 = np.array([1,2,3]) 
print(t1) 
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#可以传range
t2 = np.array(range(10))
print(t2) 
print(type(t2))
print(list(t2))  #list转回列表

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
#np自带arange
t3 = np.arange(0,10,2)
print(t3) 
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [10]:
#二维数组
import numpy as np
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)


<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]


In [11]:
#看ndarray的各种属性
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列）
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)


2
(3, 2)
6


In [15]:
four = np.array([[1,2,3],[4,5,6]])

# 修改的是原有的
four1=four
four.shape = (3,2) 
print(id(four))
print(id(four1))
print(four)
# 返回一个新的数组
four = four.reshape(3,2) 
print(four)

# 将多维变成一维数组
five = four.reshape((6,),order='C')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='C') 
print(five)
print(six)
print('-'*50)
# 拓展：数组的形状
t = np.arange(24) 
print(t)
print(t.shape)
print(t.ndim)
# 转换成二维
t1 = t.reshape((4,6)) 
print(t1)
print(t1.shape)
# 转成三维
#最前面的是零轴，零轴和最外面的括号对应
# 轴越小，越靠外，最小的轴是最外层
t2 = t.reshape((2,3,4)) 
print(t2) 
print(t2.shape)
print(t2.ndim)


1911262682448
1911262682448
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [16]:
#将数组转换为列表 tolist
a= np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()
print(type(a))
print(list_a) 
print(type(list_a))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


In [18]:
#指定dtype的目的是减少内存的使用，提高运算效率
#np.int8到np.int64
import random
f = np.array([1,2,3,4,5], dtype = np.int16) # 返回数组中每个元素的字节单位长度,dtype设置数据类型
print(f.itemsize) # 1 np.int8(一个字节)
# 获取数据类型
print(f.dtype)

# 调整数据类型
f1 = f.astype(np.int64) 
print(f1.dtype)
print(f1.itemsize) 

# 拓展随机生成小数
# 使用python语法，round是保留多少位
print(round(random.random(),2))

arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.itemsize)
print(arr.dtype)
arr1=arr.astype(np.float32)
print(arr1)
#float32精度为6-7位
#double(float64)精度是15-16位

# 取小数点后两位
print(np.round(arr,2))


2
int16
int64
8
0.47
[0.01504759 0.75437702 0.30793888 0.3414981  0.00205756 0.90944318
 0.46109341 0.04400409 0.04335634 0.57052135]
8
float64
[0.01504759 0.754377   0.30793887 0.3414981  0.00205756 0.9094432
 0.4610934  0.04400409 0.04335634 0.57052135]
[0.02 0.75 0.31 0.34 0.   0.91 0.46 0.04 0.04 0.57]


# 数组和数的计算


In [22]:
t1 = np.arange(24).reshape((6,4))
print(t1)
print("-"*20)
t2=t1.tolist()
print(t1+2) #ndarray可以与整数进行加减乘除
# print(t2+2) 不能对列表进行直接加整数操作
print("-"*20)
print(t1*2) 
print("-"*20)
print(t1/2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [23]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
print(t1)
print(t2)
print(t1+t2) 
print(t1*t2)  #是否是矩阵乘法？ 不是,是对应位置想乘


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [24]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(6).reshape((3,2))
print(t1)
print(t2) 
print(t1-t2) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1]
 [2 3]
 [4 5]]


ValueError: operands could not be broadcast together with shapes (4,6) (3,2) 

In [30]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等
t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(0,6)
print(t1)
print(t2)
t2=t2.reshape((1,6))
print(t2)
print(np.sum(t2))
print(t2.shape)
print(t1-t2)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
[[0 1 2 3 4 5]]
15
(1, 6)
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [28]:
t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(4).reshape((4,1))
print(t2)
print(t1)
print(t1-t2)


[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


# 练习轴

In [31]:
t1=np.arange(1,19).reshape((3,2,3))
print(t1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [35]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sum(a,axis=0)) # [5 7 9]
print("-"*20)
print(np.sum(a,axis=1)) # [ 6 15]
print("-"*20)
print(np.sum(a))
a=np.arange(27).reshape((3,3,3))
print(a)
print("-"*20)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
c=np.sum(a, axis=1)
print("-"*20)
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)

b=np.arange(120).reshape((2,3,4,5))
print(b)
c=np.sum(b,axis=1)
print('-'*50)
print(c)

[[1 2 3]
 [4 5 6]]
[5 7 9]
--------------------
[ 6 15]
--------------------
21
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117

# 索引和切片

In [36]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])


2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [37]:
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列  py是t1[2][3]
print('*'*20)
print(t1[[0,1,1],[0,1,3]])# 取多个不连续的值，[[行，行。。。],[列，列。。。]]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[0 7 9]


# 修改值

In [49]:
import numpy as np
t = np.arange(24).reshape(4,6)
print(t)
print('-'*50)
# # 修改某一行的值
# t[1,:]=0
#
# # 修改某一列的值
# t[:,1]=0
#
# # 修改连续多行
# t[1:3,:]=0
#
# # 修改连续多列
# t[:,1:4]=0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[1,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0
# print(t)
# 使用逻辑判断
# np.logical_and	& # np.logical_or	|
# np.logical_not		~
# t[(t>2)&(t<6)]=0	# 逻辑与
# t[(t<2)|(t>6)]=0	# 逻辑或
# t[~(t>6)]=0	# 逻辑非
# print(t)
t=t.clip(10,18)
print(t)


# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80,88],[82,81],[75,81]])
result = np.where(score<80,True,False)
print(result)
score[result]=100
score

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]
[[False False]
 [False False]
 [ True False]]


array([[ 80,  88],
       [ 82,  81],
       [100,  81]])

In [47]:
# python 的三目运算如何做
max1= 10 if 10>5 else 5
max1

10

# 数据的添加，删除与去重

In [3]:
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# 此外，输入数组的维度必须匹配，否则将生成ValueError。
'''
参 数 说 明 ：                                                                                                                                                           arr： 输 入 数 组                                                                                                                                               values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）                                                                    axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，分别为0和1的时候。当
axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。
'''
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')
print(a)
print('-'*50)
b=np.array([[7, 8, 9]])
print(b.ndim)
print(b)
print('-'*50)
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print(a)
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5], [7, 8]], axis=1))
print(a)
print('-'*50)
# # 2. numpy.insert
# # 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# # 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

a = np.array([[1, 2], [3, 4], [5, 6]])

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a,1, [11, 12]))
print('\n')
print(np.insert(a,1, [11, 12],axis=0))
# print('传递了 Axis 参数。 会广播值数组来配输入数组。')

print('沿轴  0 广播：')
print(np.insert(a, 1, 11, axis=0))
print('\n')

print('沿轴  1 广播：')
print(np.insert(a, (0,1,2), 11, axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]]
--------------------------------------------------
2
[[7 8 9]]
--------------------------------------------------
沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]]
沿轴 1 添加元素：
[[1 2 3 5 5]
 [4 5 6 7 8]]
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1 11 12  2  3  4  5  6]


[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
沿轴  0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴  1 广播：
[[11  1 11  2 11]
 [11  3 11  4 11]
 [11  5 11  6 11]]


In [60]:
#numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''
参 数 说 明 ： arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开'''
import numpy as np
a = np.arange(2,14).reshape(3,4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')
print(a)
print('删除第一行：')
print(np.delete(a,1,axis = 0))
print('\n')


print(np.delete(a,1,axis = 1))

第一个数组：
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 2  3  4  5  6  8  9 10 11 12 13]


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
删除第一行：
[[ 2  3  4  5]
 [10 11 12 13]]


[[ 2  4  5]
 [ 6  8  9]
 [10 12 13]]


AttributeError: 'numpy.ndarray' object has no attribute 'delete'

In [64]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展开
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np
a = np.array([5,2,6,2,7,5,6,9,8,2])

print ('第一个数组：')
print (a)
print ('\n')

#去除重复元素，输出的是有序序列
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
# print ('\n')

print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print(u)
print (indices)
# print ('\n')

print ('我们可以看到每个和原数组下标对应的数值：')
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')

print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)


第一个数组：
[5 2 6 2 7 5 6 9 8 2]


第一个数组的去重值：
[2 5 6 7 8 9]
去重数组的索引数组：
[2 5 6 7 8 9]
[1 0 2 4 8 7]
我们可以看到每个和原数组下标对应的数值：
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 5 4 0]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


# numpy的计算

In [67]:
import numpy as np
score = np.array([[80,88],[82,81],[75,81]])
# 1. 获取所有数据最大值
print(score)
result = np.max(score)
print(result)
print('-'*50)
# 2. 获取某一个轴上的数据最大值
result = np.max(score,axis=1)
print(result)
# 3. 获取最小值
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score,axis=0)
print(result)
# 5. 数据的比较
 # 第一个参数中的每一个数与第二个参数比较返回大的
result = np.maximum( [-2, -1, 0, 1, 2], 0 )
print(result)
 # 第一个参数中的每一个数与第二个参数比较返回小的
result = np.minimum( [-2, -1, 0, 1, 2], 0 )
print(result)
result = np.maximum( [-2, -1, 4, 1, 2], [1, 2, 3, 4, 5] )
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；

# 6. 求平均值
result = np.mean(score) # 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0) # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr	= np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
'''
[1, 2, 3]------>	|1	|2	|3	|
[4, 5, 6]------>	|5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(1))
'''
[1, 2, 3]------>	|1	|2+1	|3+2+1	|
[4, 5, 6]------>	|4	|4+5	|4+5+6	|
'''

# 8. argmin求最小值索引
result = np.argmin(score,axis=0)
res=np.min(score,axis=0) #这样我们就可以知道最小的81是第二排的，是从前往后遍历的
print(result,res)

# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)

# 10. 极 值
result = np.ptp(score,axis=None)#就是最大值和最小值的差
print(result)

# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median

'''通用函数：
numpy.sqrt(array)	平方根函数
numpy.exp(array)	e^array[i]的数组
numpy.abs/fabs(array)	计算绝对值
numpy.square(array)	计算各元素的平方 等于array	2
numpy.log/log10/log2(array)	计算各元素的各种对数
numpy.sign(array)	计算各元素正负号
numpy.isnan(array)	计算各元素是否为NaN
numpy.isinf(array)	计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array)	将array中值得整数和小数分离，作两个数组返回
numpy.ceil(array)	向上取整,也就是取比这个数大的整数
numpy.floor(array)	向下取整,也就是取比这个数小的整数
numpy.rint(array)	四舍五入
numpy.trunc(array)	向0取整
numpy.cos(array)	正弦值
numpy.sin(array)	余弦值
numpy.tan(array)	正切值

numpy.add(array1,array2)	元素级加法
numpy.subtract(array1,array2)	元素级减法
numpy.multiply(array1,array2)	元素级乘法
numpy.divide(array1,array2)	元素级除法 array1./array2
numpy.power(array1,array2)	元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2)	元素级最大值，忽略NaN
numpy.mod(array1,array2)	元素级求模
numpy.copysign(array1,array2)	将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''

[[80 88]
 [82 81]
 [75 81]]
88
--------------------------------------------------
[88 82 81]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 4 4 5]
81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
[2 1] [75 81]
[2.94392029 3.29983165]
13


'通用函数：\nnumpy.sqrt(array)\t平方根函数\nnumpy.exp(array)\te^array[i]的数组\nnumpy.abs/fabs(array)\t计算绝对值\nnumpy.square(array)\t计算各元素的平方 等于array\t2\nnumpy.log/log10/log2(array)\t计算各元素的各种对数\nnumpy.sign(array)\t计算各元素正负号\nnumpy.isnan(array)\t计算各元素是否为NaN\nnumpy.isinf(array)\t计算各元素是否为NaN\nnumpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数\nnumpy.modf(array)\t将array中值得整数和小数分离，作两个数组返回\nnumpy.ceil(array)\t向上取整,也就是取比这个数大的整数\nnumpy.floor(array)\t向下取整,也就是取比这个数小的整数\nnumpy.rint(array)\t四舍五入\nnumpy.trunc(array)\t向0取整\nnumpy.cos(array)\t正弦值\nnumpy.sin(array)\t余弦值\nnumpy.tan(array)\t正切值\n\nnumpy.add(array1,array2)\t元素级加法\nnumpy.subtract(array1,array2)\t元素级减法\nnumpy.multiply(array1,array2)\t元素级乘法\nnumpy.divide(array1,array2)\t元素级除法 array1./array2\nnumpy.power(array1,array2)\t元素级指数 array1.^array2\nnumpy.maximum/minimum(array1,aray2) 元素级最大值\nnumpy.fmax/fmin(array1,array2)\t元素级最大值，忽略NaN\nnumpy.mod(array1,array2)\t元素级求模\nnumpy.copysign(array1,array2)\t将第二个数组中值得符号复制给第一个数组中值\nnumpy.greater/greater_equal/less/less_equal/equa

In [71]:
np.log(32)


3.4657359027997265

# 数组的拼接

In [75]:
# 有的时候我们需要将两个数据加起来一起研究分析，我们就可以将其进行拼接然后分析
import numpy as np
# 1. 根据轴连接的数组序列，concatenate没有改变数组的维度
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# # 要求a,b两个数组的维度相同
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))
print('-'*50)
print(np.stack([a,b],axis=0))

# # 2. 根据轴进行堆叠，2维会变为3维

arrays = [np.arange(12).reshape(3, 4) for _ in range(10)]
print(arrays)
print(len(arrays))
print ('沿轴 0 连接两个数组：')
result0=np.stack(arrays,axis= 0)
print (result0.shape)  #(10,3,4)
print (result0)
print('-'*50)
print ('沿轴 1 连接两个数组：')
print(arrays[0])
result1=np.stack(arrays,axis = 1)
print (result1.shape)  #(3,10,4)
print (result1)
print('-'*50)
print ('沿轴 2连接两个数组：这里-1和2是等价的')
result2=np.stack(arrays,axis = -1)
print(arrays[0])
print(result2.shape)
print(result2)
print('*'*50)
# # # 3. 矩阵垂直拼接，vstack没有增加维数
v1 = [[0,1,2,3,4,5],
	[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
	[18,19,20,21,22,23]]
result = np.vstack((v1,v2))
print(result)

# # # 4. 矩阵水平拼接
v1 = [[0,1,2,3,4,5],
	[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
	[18,19,20,21,22,23]]
result = np.hstack((v1,v2))
print(result)



沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]
--------------------------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
10
沿轴 0 连接两个数组：
(10, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [

# 分割

In [78]:
# 1. 将一个数组分割为多个子数组
'''
参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分
'''
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
print ('将数组分为三个大小相等的子数组：')
b = np.split(arr,3)
print (b)
c=np.hsplit(arr,3)
print (c)

# # 2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
d=np.random.random((2, 6))
print(d)
harr = np.floor(10*d)
print ('原array：')
print(harr)
print(harr.dtype)
print(np.ceil(10*d))
print ('拆分后：')


# # 3.numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4,4)

print ('第一个数组：')
print (a)
print ('\n')

print ('竖直分割：')
b = np.vsplit(a,2)
print (b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
[[0.87611729 0.09377593 0.13255357 0.59026114 0.87934422 0.33762201]
 [0.52666173 0.11288299 0.11209971 0.74463713 0.08441255 0.00093828]]
原array：
[[8. 0. 1. 5. 8. 3.]
 [5. 1. 1. 7. 0. 0.]]
float64
[[9. 1. 2. 6. 9. 4.]
 [6. 2. 2. 8. 1. 1.]]
拆分后：
[array([[8., 0.],
       [5., 1.]]), array([[1., 5.],
       [1., 7.]]), array([[8., 3.],
       [0., 0.]])]
第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# numpy inf和nan

In [80]:
'''
C 语言中表示最大的正整数值是 0x7FFF FFFF，最小的负整数是 0x8000 0000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有	float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现inf呢？ 比如一个数字除以0，Python中会报错，但是numpy中会是一个inf或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。任何与其做运算结果都是 nan
'''
import numpy as np
# 创建一个nan和inf #
a = np.nan  #nan代表not a number，不是数值，从文档中读取数值时，读取了空
b = np.inf
print(a,type(a))
print(b,type(b))

# --判断数组中为nan的个数
t = np.arange(24,dtype=float).reshape(4,6)

# 将三行四列的数改成nan
t[3,4] = np.nan
t[2,4] = np.nan
print(t)
# 可以使用np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))
# 并 且  np.nan != np.nan	结果 是TRUE
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.nan==np.nan)
print('-'*50)
print(t!=t)
print(np.count_nonzero(t != t))

# 将nan替换为0
t[np.isnan(t)] = 0
# t[t!=t]=0
print(t)

# ----------练习： 处理数组中nan
t = np.arange(24).reshape(4,6).astype('float')
#
# 将数组中的一部分替换nan
t[1,3:] = np.nan
print(t)
print('-'*50)
print(t.shape)
# 遍历每一列，然后判断每一列是否有nan, column
for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:,i]

    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 条件成立说明含有nan
    if nan_num != 0:
        # 将这一列不为nan的数据拿出来
        temp_col_not_nan = temp_col[temp_col == temp_col]
        print(temp_col_not_nan)
        # 将nan替换成这一列的平均值
        temp_col[np.isnan( temp_col )] = np.mean( temp_col_not_nan )

print(t)

nan <class 'float'>
inf <class 'float'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]
23
False
--------------------------------------------------
[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
2
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
(4, 6)
[ 3. 15. 21.]
[ 4. 16. 22.]
[ 5. 17. 23.]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [89]:
t = np.arange(24).reshape(4,6).astype('float')
#
# 将数组中的一部分替换nan
t[1,3:] = np.nan
np.mean(t,axis=0)

array([ 9., 10., 11., nan, nan, nan])

In [86]:
246/24

10.25

In [91]:
np.inf==np.inf

True

In [92]:
t = np.arange(24).reshape(4,6).astype('float')
#
# 将数组中的一部分替换nan
t[1,3:] = np.nan

t1=np.arange(24).reshape(4,6).astype('float')
t+t1

array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [93]:
print(-np.inf==-np.inf)
arr=np.array([-1,0])
print(arr)
print(arr[0]/arr[1])  #1除0就会得到inf

True
[-1  0]
-inf


C:\Users\Administrator\AppData\Local\Temp\ipykernel_2216\2884963993.py:4: RuntimeWarning: divide by zero encountered in long_scalars
  print(arr[0]/arr[1])  #1除0就会得到inf


# 转置和轴滚动

In [94]:
#对换数组的维度
import numpy as np
a = np.arange(12).reshape(3,4)
print ('原数组：')
print (a )
print ('\n')

print ('对换数组：')
print (np.transpose(a))
print(a)

# 与transpose一致
a = np.arange(12).reshape(3,4)

print ('原数组：')
print (a)
print ('\n')

print ('转置数组：')
print (a.T)

# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4,6)
re = t1.swapaxes(1,0)

print (' 原 数 组 ：')
print (t1)
print ('\n')
print(re.shape)
print ('调用 swapaxes 函数后的数组：')
print (re)
# 交换轴，到机器学习，深度学习，只要看shape
# 从内往外
t3=np.arange(60).reshape(3,4,5)
print(t3)
print('-'*50)
t3=np.swapaxes(t3,0,2)
print(t3.shape)
print(t3)


原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


(6, 4)
调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
--------------------------------------------------
(5, 4, 3)
[[[ 0 20 40]
  [ 5 25 45]
  [10 30 50]
  [15 35 55]]

 [[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]


In [102]:
# 轴滚动
a = np.ones((3,4,5,6))
np.rollaxis(a, 3,start=0).shape

(6, 3, 4, 5)

In [105]:
#学会使用copy
b=np.array([1,2,3])
a=b.copy()
a
b[0]=3
print(b)
a

[3 2 3]


array([3, 2, 3])

In [4]:
import numpy as np
0*np.inf

nan